Added the bug report and feature request form
Azure/k8s-set-context pull request #63
Opened 2022-08-31 18:08 UTC by Vidya2606

2022-08-31 20:02 UTC, OliverMKing requested changes

2022-08-31 20:02 UTC, OliverMKing commented on .github/ISSUE_TEMPLATE/config.yml
> +   - name: GitHub Action "aks-set-context" Support
This link and name is wrong. It's pointing to aks-set-context

2022-09-01 15:16 UTC, OliverMKing approved these changes

2022-09-06 17:18 UTC, bfoley13 approved these changes

2022-09-06 21:33 UTC, merged